version: "3.7"
services:
  quickmq:
    build: .
    # image: ochom/quickmq:latest
    container_name: quickmq
    ports:
      - "3456:8080"
    environment:
      QUICK_USER: admin
      QUICK_PASSWORD: admin
    volumes:
      - ./data:/var/pubsub/data/
