version: '3.7'
services:
  my-quick-pubsub:
    build: .
    ports:
      - "3456:8080"
    environment:
      QUICK_USER: admin
      QUICK_PASSWORD: admin
    volumes:
      - ./data:/var/pubsub/data/
