version: '3.7'
services:
  my-quick-pubsub:
    build: .
    ports:
      - "8080:8080"
    environment:
      QUICK_USER: admin
      QUICK_PASSWORD: admin
    volumes:
      - ./pubsub.db:/pubsub.db

